### ISSUE TITLE
still failing

### ISSUE THREAD

**Issue by vjcitn** [zhenkewu/baker_example#2]
> mcmc_options <- list(debugstatus = !TRUE,
 +                      individual.pred = !TRUE, 
 +                      ppd    .... [TRUNCATED] 

 > # Record the settings of current analysis: 
 > # data clean options:
 > clean_options <- list (#raw_meas_dir       =  file.path("~/data/perch","PQ_27JU ..." ... [TRUNCATED] 

 > dput(clean_options,file.path(mcmc_options$result.folder,"data_clean_options.txt"))
Error in file(file, "wt") : cannot open the connection
In addition: Warning messages:
1: In dir.create(dated_strat_name) :
  cannot create dir '/Users/stvjc/Downloads/run_baker_example/scn_3_mixiter_1', reason 'No such file or directory'
2: In dir.create(result_folder) :
  cannot create dir '/Users/stvjc/Downloads/run_baker_example/scn_3_mixiter_1/rep_1_kfit_2', reason 'No such file or directory'
3: In file(file, "wt") :
  cannot open file '/Users/stvjc/Downloads/run_baker_example/scn_3_mixiter_1/rep_1_kfit_2/data_clean_options.txt': No such file or directory

Enter a frame number, or 0 to exit   

1: source("simulated_example_nplcm.R", echo = TRUE)
2: withVisible(eval(ei, envir))
3: eval(ei, envir)
4: eval(ei, envir)
5: simulated_example_nplcm.R#200: dput(clean_options, file.path(mcmc_options$r
6: file(file, "wt")

I wonder whether a tempfile() discipline could help avoid collisions.  I really can't tell what is going wrong here, it may have to do with CODA output availability?

%vjcair> pwd
/Users/stvjc/Research/OSLER_ZEGER/baker_example
%vjcair> git status simu*R
On branch master
Your branch is up-to-date with 'origin/master'.
nothing to commit, working tree clean

> sessionInfo()
R Under development (unstable) (2016-10-26 r71594)
Platform: x86_64-apple-darwin13.4.0 (64-bit)
Running under: OS X El Capitan 10.11.6

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] baker_0.6-3   rmarkdown_1.2

loaded via a namespace (and not attached):
 [1] backports_1.0.4 magrittr_1.5    rprojroot_1.1   tools_3.4.0    
 [5] htmltools_0.3.5 Rcpp_0.12.8     stringi_1.1.2   knitr_1.15.1   
 [9] stringr_1.1.0   digest_0.6.10   evaluate_0.10

**Comment by zhenkewu** [comment]
Thanks, Vince. I just updated baker. Do you want to quickly try it again? If it's a directory issue, a quick fix could be to hand-create those folders beforehand just to test the code. I'll deal with automatic creation of folders soon. Thanks! Zhenke

**Comment by vjcitn** [comment]
hi you are hardcoding operations in ~/Downloads.  This is not portable.
When that is fixed, we still have an error because coda is not being run?

also this error message about Filed to open file seems strange

%vjcair> ls -tl
./run_baker_example/scn_3_mixiter_1/rep_1_kfit_2/model_NoReg.bug

-rw-r--r--  1 stvjc  staff  3391 Dec 20 20:08
./run_baker_example/scn_3_mixiter_1/rep_1_kfit_2/model_NoReg.bug
...

Clearing data table

Failed to open file
./run_baker_example/scn_3_mixiter_1/rep_1_kfit_2/model_NoReg.bug

*Error in file(file, "rt") : cannot open the connection*

*In addition: Warning message:*

*In file(file, "rt") :*

*  cannot open file 'CODAindex.txt': No such file or directory*


Enter a frame number, or 0 to exit


 1: source("simulated_example_nplcm.R", echo = TRUE)

 2: withVisible(eval(ei, envir))

 3: eval(ei, envir)

 4: eval(ei, envir)

 5: simulated_example_nplcm.R#206: nplcm(data_nplcm, model_options,
mcmc_option

 6: nplcm_fit_NoReg(data_nplcm, model_options, mcmc_options)

 7: R2jags::jags2(data = in_data, inits = in_init, parameters.to.save =
out_par

 8: jags.sims(parameters.to.save = parameters.to.save, n.chains = n.chains,
n.i

 9: read.table("CODAindex.txt", header = FALSE)

10: file(file, "rt")

**Comment by zhenkewu** [comment]
Hi Vince, 

I tried the code again. I didn't find hardcoding. One specifies the working directory, the .R will automatically create folder, subfolders and files. From your error messages, it could be the folders are not created in the first place. Maybe it's administrative privilege issue?  CODA package outputs error because it couldn't find the posterior sample files.

Thanks!
Zhenke

I ran the following code, on my Mac (OSX) and cluster, both passed. 

```r
source_github <- function(u) {
  # load package
  require(RCurl)
  
  # read script lines from website
  script <- getURL(u, ssl.verifypeer = FALSE)
  
  # parase lines and evealuate in the global environement
  eval(parse(text = script))
}

devtools::install_github("zhenkewu/baker")

sessionInfo()
source("https://raw.githubusercontent.com/zhenkewu/baker_example/master/simulated_example_nplcm.R")
```


```r
> sessionInfo()
R version 3.3.2 (2016-10-31)
Platform: x86_64-apple-darwin13.4.0 (64-bit)
Running under: macOS Sierra 10.12.3

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods  
[7] base     

other attached packages:
[1] baker_0.6-3

loaded via a namespace (and not attached):
 [1] httr_1.2.1            binom_1.1-1          
 [3] splines_3.3.2         assertthat_0.1       
 [5] sp_1.2-3              stats4_3.3.2         
 [7] robustbase_0.92-6     R2WinBUGS_2.1-21     
 [9] VIM_4.6.0             lattice_0.20-34      
[11] quantreg_5.29         digest_0.6.10        
[13] RColorBrewer_1.1-2    minqa_1.2.4          
[15] colorspace_1.3-1      R2jags_0.5-7         
[17] Matrix_1.2-7.1        plyr_1.8.4           
[19] multicool_0.1-9       pcaPP_1.9-61         
[21] devtools_1.12.0       misc3d_0.8-4         
[23] SparseM_1.74          mvtnorm_1.0-5        
[25] scales_0.4.1          rjags_4-6            
[27] lme4_1.1-12           MatrixModels_0.4-1   
[29] git2r_0.15.0          tibble_1.2           
[31] mgcv_1.8-15           car_2.1-3            
[33] ggplot2_2.2.0         withr_1.0.2          
[35] nnet_7.3-12           mvbutils_2.7.4.1     
[37] lazyeval_0.2.0        pbkrtest_0.4-6       
[39] magrittr_1.5          mclust_5.2           
[41] memoise_1.0.0         ks_1.10.4            
[43] GGally_1.3.0          laeken_0.4.6         
[45] nlme_3.1-128          MASS_7.3-45          
[47] class_7.3-14          tools_3.3.2          
[49] data.table_1.10.0     trimcluster_0.1-2    
[51] stringr_1.1.0         kernlab_0.9-25       
[53] munsell_0.4.3         cluster_2.0.5        
[55] fpc_2.1-10            pls_2.5-0            
[57] e1071_1.6-7           vcd_1.4-3            
[59] grid_3.3.2            nloptr_1.0.4         
[61] cvTools_0.3.2         labeling_0.3         
[63] boot_1.3-18           gtable_0.2.0         
[65] codetools_0.2-15      curl_1.1             
[67] abind_1.4-5           flexmix_2.3-13       
[69] reshape_0.8.6         R6_2.2.0             
[71] reshape2_1.4.2        rrcov_1.4-3          
[73] gridExtra_2.2.1       robCompositions_2.0.2
[75] zoo_1.7-13            prabclus_2.2-6       
[77] sROC_0.1-2            KernSmooth_2.23-15   
[79] modeltools_0.2-21     stringi_1.1.2        
[81] parallel_3.3.2        Rcpp_0.12.8          
[83] rgl_0.95.1441         DEoptimR_1.0-6       
[85] diptest_0.75-7        coda_0.18-1          
[87] lmtest_0.9-34        
> source("https://raw.githubusercontent.com/zhenkewu/baker_example/master/simulated_example_nplcm.R")
== Visualizing pairwise log odds ratios for bronze-standard data set:  1 :  MBS1 . ==
==[baker] Results stored in: == 
 ~/Downloads/run_baker_example/scn_3_mixiter_1/rep_1_kfit_2 
Welcome to JAGS 4.2.0 on Wed Dec 21 00:39:04 2016
JAGS is free software and comes with ABSOLUTELY NO WARRANTY
Loading module: basemod: ok
Loading module: bugs: ok
Deleting model
Clearing data table 
Reading data file jagsdata.txt
Compiling model graph
   Resolving undeclared variables
   Allocating nodes
Graph information:
   Observed stochastic nodes: 6000
   Unobserved stochastic nodes: 9029
   Total graph size: 195169
Reading initial values file jagsinits1.txt
Initializing model
Updating 1
| 1
* 100%
NOTE: Stopping adaptation

Updating 99
-------------------------------------------------| 99
************************************************** 100%

 == Plotting Panels of Measurements and Marginal Posterior of Etiology Fractions == 

 == Plotting BrS Slice:  1 :  MBS1
 == Plotting pies == 

 == Done. == 

 == Plotting Panels of Measurements and Marginal Posterior of Etiology Fractions == 

 == Plotting BrS Slice:  1 :  MBS1
 == Plotting pies == 

 == Done. == 
trying URL 'https://raw.githubusercontent.com/zhenkewu/baker_example/master/pathogen_category_simulation.csv'
Content type 'text/plain; charset=utf-8' length 154 bytes
==================================================
downloaded 154 bytes

==A figure is generated for model checking: pairwise standardized log odds ratio difference (SLORD). 
          Stored in  ~/Downloads/run_baker_example/scn_3_mixiter_1/rep_1_kfit_2  ====Plotting for model checking: frequent BrS measurements patterns. ==
Warning: Ignoring unknown aesthetics: width
Warning: Ignoring unknown aesthetics: yintercept
Warning: Ignoring unknown aesthetics: width
Warning: Ignoring unknown aesthetics: yintercept
```

**Comment by vjcitn** [comment]
thanks, getting further now.  still failing towards end.  see attached tiff
for hardcode folder
in example, line 22

--- see below for error

> result_folder <- mcmc_options$result.folder


> # plot data, prior, and posteriors for all causitive pathogens:

> pdf(file.path(result_folder,"panels_plot.pdf"), height=10, width =20)


> suppressWarnings(plot_panels(result_folder,bg_color=NULL))


 == Plotting Panels of Measurements and Marginal Posterior of Etiology
Fractions ==

*Error in plot_BrS_panel(s, data_nplcm, model_options, clean_options,
bugs.dat,  : *

*  could not find function "binom.confint"*

**Comment by zhenkewu** [comment]
Hi Vince,

Thanks! Just made two changes:
1) used the `tempdir()` on line 23 to remove the hardcoded directory.
2) added `library(binom)`, because the `could not find function binom.confit` error means the package it belongs to, `binom`, is not attached.

Zhenke

**Comment by zhenkewu** [comment]
Hi Vince, did you have a chance to test it.

**Comment by vjcitn** [comment]
yes, last time i looked it was running.  sorry that i did not notify.

**Comment by zhenkewu** [comment]
Great!
